package storymodel4s.amr

/** Generated by tools/penman-oracle.py against Penman 1.3.1. Do not edit. */
object PenmanGolden:
  final case class Case(
      name: String,
      input: String,
      top: String,
      triples: Vector[(String, String, String, Boolean)]
  )

  val cases: Vector[Case] = Vector(
    Case(
      "g01-control",
      "# ::id g01-control\n(w / want-01\n   :ARG0 (b / boy)\n   :ARG1 (g / go-02\n            :ARG0 b))",
      "w",
      Vector(
        ("instance", "w", "want-01", false),
        ("ARG0", "w", "b", true),
        ("instance", "b", "boy", false),
        ("ARG1", "w", "g", true),
        ("instance", "g", "go-02", false),
        ("ARG0", "g", "b", true)
      )
    ),
    Case(
      "g02-inverse-top",
      "# ::id g02-inverse-top\n(b / boy\n   :ARG0-of (s / sing-01))",
      "b",
      Vector(
        ("instance", "b", "boy", false),
        ("ARG0", "s", "b", true),
        ("instance", "s", "sing-01", false)
      )
    ),
    Case(
      "g03-reentrancy-embedded",
      "# ::id g03-reentrancy-embedded\n(s / say-01\n   :ARG0 (g / girl)\n   :ARG1 (l / like-01\n            :ARG0 g\n            :ARG1 (b / boy)))",
      "s",
      Vector(
        ("instance", "s", "say-01", false),
        ("ARG0", "s", "g", true),
        ("instance", "g", "girl", false),
        ("ARG1", "s", "l", true),
        ("instance", "l", "like-01", false),
        ("ARG0", "l", "g", true),
        ("ARG1", "l", "b", true),
        ("instance", "b", "boy", false)
      )
    ),
    Case(
      "g04-polarity",
      "# ::id g04-polarity\n(g / go-02\n   :ARG0 (b / boy)\n   :polarity -)",
      "g",
      Vector(
        ("instance", "g", "go-02", false),
        ("ARG0", "g", "b", true),
        ("instance", "b", "boy", false),
        ("polarity", "g", "-", false)
      )
    ),
    Case(
      "g05-name",
      "# ::id g05-name\n(p / person\n   :name (n / name\n            :op1 \"Barack\"\n            :op2 \"Obama\"))",
      "p",
      Vector(
        ("instance", "p", "person", false),
        ("name", "p", "n", true),
        ("instance", "n", "name", false),
        ("op1", "n", "\"Barack\"", false),
        ("op2", "n", "\"Obama\"", false)
      )
    ),
    Case(
      "g06-quantity",
      "# ::id g06-quantity\n(d / distance-quantity\n   :quant 5\n   :unit (m / mile))",
      "d",
      Vector(
        ("instance", "d", "distance-quantity", false),
        ("quant", "d", "5", false),
        ("unit", "d", "m", true),
        ("instance", "m", "mile", false)
      )
    ),
    Case(
      "g07-date",
      "# ::id g07-date\n(d / date-entity\n   :year 2012\n   :month 2\n   :day 29)",
      "d",
      Vector(
        ("instance", "d", "date-entity", false),
        ("year", "d", "2012", false),
        ("month", "d", "2", false),
        ("day", "d", "29", false)
      )
    ),
    Case(
      "g08-coordination",
      "# ::id g08-coordination\n(a / and\n   :op1 (b / boy)\n   :op2 (g / girl))",
      "a",
      Vector(
        ("instance", "a", "and", false),
        ("op1", "a", "b", true),
        ("instance", "b", "boy", false),
        ("op2", "a", "g", true),
        ("instance", "g", "girl", false)
      )
    ),
    Case(
      "g09-multi-sentence",
      "# ::id g09-multi-sentence\n(m / multi-sentence\n   :snt1 (l / leave-11\n            :ARG0 (b / boy))\n   :snt2 (c / cry-02\n            :ARG0 (g / girl)))",
      "m",
      Vector(
        ("instance", "m", "multi-sentence", false),
        ("snt1", "m", "l", true),
        ("instance", "l", "leave-11", false),
        ("ARG0", "l", "b", true),
        ("instance", "b", "boy", false),
        ("snt2", "m", "c", true),
        ("instance", "c", "cry-02", false),
        ("ARG0", "c", "g", true),
        ("instance", "g", "girl", false)
      )
    ),
    Case(
      "g10-legitimate-cycle",
      "# ::id g10-legitimate-cycle\n(w / want-01\n   :ARG0 (b / boy)\n   :ARG1 (b2 / believe-01\n             :ARG0 (g / girl)\n             :ARG1 w))",
      "w",
      Vector(
        ("instance", "w", "want-01", false),
        ("ARG0", "w", "b", true),
        ("instance", "b", "boy", false),
        ("ARG1", "w", "b2", true),
        ("instance", "b2", "believe-01", false),
        ("ARG0", "b2", "g", true),
        ("instance", "g", "girl", false),
        ("ARG1", "b2", "w", true)
      )
    ),
    Case(
      "g11-metadata-and-alignment",
      "# ::id g11-metadata-and-alignment ::snt Once when I was six years old I saw a picture.\n(s / see-01~e.6\n   :ARG0 (i / i~e.5)\n   :ARG1 (p / picture~e.8)\n   :time (o / once~e.0))",
      "s",
      Vector(
        ("instance", "s", "see-01", false),
        ("ARG0", "s", "i", true),
        ("instance", "i", "i", false),
        ("ARG1", "s", "p", true),
        ("instance", "p", "picture", false),
        ("time", "s", "o", true),
        ("instance", "o", "once", false)
      )
    ),
    Case(
      "g12-string-escape",
      "# ::id g12-string-escape\n(p / person\n   :name (n / name\n            :op1 \"O\\\"Brien\"))",
      "p",
      Vector(
        ("instance", "p", "person", false),
        ("name", "p", "n", true),
        ("instance", "n", "name", false),
        ("op1", "n", "\"O\\\"Brien\"", false)
      )
    ),
    Case(
      "g13-negative-number",
      "# ::id g13-negative-number\n(t / temperature-quantity\n   :quant -5\n   :scale (c / celsius))",
      "t",
      Vector(
        ("instance", "t", "temperature-quantity", false),
        ("quant", "t", "-5", false),
        ("scale", "t", "c", true),
        ("instance", "c", "celsius", false)
      )
    ),
    Case(
      "g14-domain",
      "# ::id g14-domain\n(t / tall\n   :domain (g / girl))",
      "t",
      Vector(
        ("instance", "t", "tall", false),
        ("domain", "t", "g", true),
        ("instance", "g", "girl", false)
      )
    ),
    Case(
      "g15-consist-of",
      "# ::id g15-consist-of\n(r / ring\n   :consist-of (g / gold))",
      "r",
      Vector(
        ("instance", "r", "ring", false),
        ("consist-of", "r", "g", true),
        ("instance", "g", "gold", false)
      )
    ),
    Case(
      "g16-imperative",
      "# ::id g16-imperative\n(g / go-02\n   :ARG0 (y / you)\n   :mode imperative)",
      "g",
      Vector(
        ("instance", "g", "go-02", false),
        ("ARG0", "g", "y", true),
        ("instance", "y", "you", false),
        ("mode", "g", "imperative", false)
      )
    ),
    Case(
      "g17-amr-unknown",
      "# ::id g17-amr-unknown\n(f / find-01\n   :ARG0 (y / you)\n   :ARG1 (a / amr-unknown))",
      "f",
      Vector(
        ("instance", "f", "find-01", false),
        ("ARG0", "f", "y", true),
        ("instance", "y", "you", false),
        ("ARG1", "f", "a", true),
        ("instance", "a", "amr-unknown", false)
      )
    ),
    Case(
      "g18-obligation",
      "# ::id g18-obligation\n(o / obligate-01\n   :ARG1 (b / boy)\n   :ARG2 (g / go-02\n            :ARG0 b))",
      "o",
      Vector(
        ("instance", "o", "obligate-01", false),
        ("ARG1", "o", "b", true),
        ("instance", "b", "boy", false),
        ("ARG2", "o", "g", true),
        ("instance", "g", "go-02", false),
        ("ARG0", "g", "b", true)
      )
    ),
    Case(
      "g19-deep-reentrancy",
      "# ::id g19-deep-reentrancy\n(w / want-01\n   :ARG0 (b / boy)\n   :ARG1 (b2 / believe-01\n             :ARG0 (g / girl)\n             :ARG1 (l / like-01\n                      :ARG0 g\n                      :ARG1 b)))",
      "w",
      Vector(
        ("instance", "w", "want-01", false),
        ("ARG0", "w", "b", true),
        ("instance", "b", "boy", false),
        ("ARG1", "w", "b2", true),
        ("instance", "b2", "believe-01", false),
        ("ARG0", "b2", "g", true),
        ("instance", "g", "girl", false),
        ("ARG1", "b2", "l", true),
        ("instance", "l", "like-01", false),
        ("ARG0", "l", "g", true),
        ("ARG1", "l", "b", true)
      )
    ),
    Case(
      "g20-org-role",
      "# ::id g20-org-role\n(p / person\n   :ARG0-of (h / have-org-role-91\n               :ARG1 (c / country\n                        :name (n / name\n                                 :op1 \"France\"))\n               :ARG2 (p2 / president)))",
      "p",
      Vector(
        ("instance", "p", "person", false),
        ("ARG0", "h", "p", true),
        ("instance", "h", "have-org-role-91", false),
        ("ARG1", "h", "c", true),
        ("instance", "c", "country", false),
        ("name", "c", "n", true),
        ("instance", "n", "name", false),
        ("op1", "n", "\"France\"", false),
        ("ARG2", "h", "p2", true),
        ("instance", "p2", "president", false)
      )
    ),
    Case(
      "g21-time-weekday",
      "# ::id g21-time-weekday\n(g / go-02\n   :ARG0 (b / boy)\n   :time (d / date-entity\n            :weekday (t / tuesday)))",
      "g",
      Vector(
        ("instance", "g", "go-02", false),
        ("ARG0", "g", "b", true),
        ("instance", "b", "boy", false),
        ("time", "g", "d", true),
        ("instance", "d", "date-entity", false),
        ("weekday", "d", "t", true),
        ("instance", "t", "tuesday", false)
      )
    ),
    Case(
      "g22-decimal",
      "# ::id g22-decimal\n(t / temperature-quantity\n   :quant 1.5\n   :scale (k / kelvin))",
      "t",
      Vector(
        ("instance", "t", "temperature-quantity", false),
        ("quant", "t", "1.5", false),
        ("scale", "t", "k", true),
        ("instance", "k", "kelvin", false)
      )
    ),
    Case(
      "g23-string-with-space",
      "# ::id g23-string-with-space\n(c / city\n   :name (n / name\n            :op1 \"New York\"))",
      "c",
      Vector(
        ("instance", "c", "city", false),
        ("name", "c", "n", true),
        ("instance", "n", "name", false),
        ("op1", "n", "\"New York\"", false)
      )
    ),
    Case(
      "g24-role-alignment",
      "# ::id g24-role-alignment\n(b / boy~e.1\n   :ARG0-of~e.2 (s / sing-01~e.2))",
      "b",
      Vector(
        ("instance", "b", "boy", false),
        ("ARG0", "s", "b", true),
        ("instance", "s", "sing-01", false)
      )
    ),
    Case(
      "g25-wiki-dash",
      "# ::id g25-wiki-dash\n(c / country\n   :wiki -\n   :name (n / name\n            :op1 \"Narnia\"))",
      "c",
      Vector(
        ("instance", "c", "country", false),
        ("wiki", "c", "-", false),
        ("name", "c", "n", true),
        ("instance", "n", "name", false),
        ("op1", "n", "\"Narnia\"", false)
      )
    ),
    Case(
      "g26-two-inverse-chain",
      "# ::id g26-two-inverse-chain\n(m / man\n   :ARG0-of (s / see-01\n               :ARG1 (d / dog\n                        :ARG1-of (b / bite-01\n                                    :ARG0 m))))",
      "m",
      Vector(
        ("instance", "m", "man", false),
        ("ARG0", "s", "m", true),
        ("instance", "s", "see-01", false),
        ("ARG1", "s", "d", true),
        ("instance", "d", "dog", false),
        ("ARG1", "b", "d", true),
        ("instance", "b", "bite-01", false),
        ("ARG0", "b", "m", true)
      )
    ),
    Case(
      "g27-shared-literal",
      "# ::id g27-shared-literal\n(a / and\n   :op1 (c / cost-01\n           :ARG1 (b / book)\n           :ARG2 (m / monetary-quantity\n                    :quant 5\n                    :unit (d / dollar)))\n   :op2 (c2 / cost-01\n            :ARG1 (p / pen)\n            :ARG2 (m2 / monetary-quantity\n                      :quant 5\n                      :unit (d2 / dollar))))",
      "a",
      Vector(
        ("instance", "a", "and", false),
        ("op1", "a", "c", true),
        ("instance", "c", "cost-01", false),
        ("ARG1", "c", "b", true),
        ("instance", "b", "book", false),
        ("ARG2", "c", "m", true),
        ("instance", "m", "monetary-quantity", false),
        ("quant", "m", "5", false),
        ("unit", "m", "d", true),
        ("instance", "d", "dollar", false),
        ("op2", "a", "c2", true),
        ("instance", "c2", "cost-01", false),
        ("ARG1", "c2", "p", true),
        ("instance", "p", "pen", false),
        ("ARG2", "c2", "m2", true),
        ("instance", "m2", "monetary-quantity", false),
        ("quant", "m2", "5", false),
        ("unit", "m2", "d2", true),
        ("instance", "d2", "dollar", false)
      )
    ),
    Case(
      "g28-prep-out-of",
      "# ::id g28-prep-out-of\n(l / leave-11\n   :ARG0 (b / boy)\n   :prep-out-of (h / house))",
      "l",
      Vector(
        ("instance", "l", "leave-11", false),
        ("ARG0", "l", "b", true),
        ("instance", "b", "boy", false),
        ("prep-out-of", "l", "h", true),
        ("instance", "h", "house", false)
      )
    ),
    Case(
      "g29-prep-on-behalf-of",
      "# ::id g29-prep-on-behalf-of\n(a / act-01\n   :ARG0 (l / lawyer)\n   :prep-on-behalf-of (c / client))",
      "a",
      Vector(
        ("instance", "a", "act-01", false),
        ("ARG0", "a", "l", true),
        ("instance", "l", "lawyer", false),
        ("prep-on-behalf-of", "a", "c", true),
        ("instance", "c", "client", false)
      )
    ),
    Case(
      "g30-triple-letter-variable",
      "# ::id g30-triple-letter-variable\n(s / see-01\n   :ARG0 (iii / i)\n   :ARG1 (d / dog\n            :ARG0-of (b / bark-01)))",
      "s",
      Vector(
        ("instance", "s", "see-01", false),
        ("ARG0", "s", "iii", true),
        ("instance", "iii", "i", false),
        ("ARG1", "s", "d", true),
        ("instance", "d", "dog", false),
        ("ARG0", "b", "d", true),
        ("instance", "b", "bark-01", false)
      )
    )
  )
