#!/usr/bin/env python3
"""Differential oracle for the Scala PENMAN reader.

Reads PENMAN documents (blank-line separated) from a file or stdin, decodes each with the pinned
Python `penman` library, and prints JSON records with the canonical triple list (inverse roles
normalised to their direct orientation) and Penman's re-encoded string. Optionally writes a Scala
golden-data source so released tests stay Python-free.

Usage:
  penman-oracle.py fixtures.txt                # JSON to stdout
  penman-oracle.py fixtures.txt --scala PATH   # also write Scala golden file
"""
import json
import sys

import penman
from penman.models.noop import model as noop_model
from penman.models.amr import model as amr_model


def triples_of(graph):
    """Canonical triples with inverse roles flipped, as (source, role, target, is_node)."""
    variables = set(graph.variables())
    out = []
    for src, role, tgt in graph.triples:
        if role == ":instance":
            out.append(["instance", src, tgt, False])
            continue
        if role.endswith("-of") and role not in (":consist-of",) and tgt in variables:
            src, tgt, role = tgt, src, role[:-3]
        out.append([role.lstrip(":"), src, tgt, tgt in variables])
    return out


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    text = open(argv[1], encoding="utf-8").read()
    scala_path = None
    if "--scala" in argv:
        scala_path = argv[argv.index("--scala") + 1]
    blocks = [b.strip() for b in text.split("\n\n") if b.strip()]
    records = []
    for i, block in enumerate(blocks):
        graph = penman.decode(block, model=noop_model)
        records.append(
            {
                "index": i,
                "input": block,
                "top": graph.top,
                "variables": sorted(graph.variables()),
                "triples": triples_of(graph),
                "reencoded": penman.encode(graph, model=noop_model),
                "metadata": graph.metadata,
                "penman_version": penman.__version__,
            }
        )
    json.dump(records, sys.stdout, indent=1)
    if scala_path:
        with open(scala_path, "w", encoding="utf-8") as fh:
            fh.write("package storymodel4s.amr\n\n")
            fh.write(
                "/** Generated by tools/penman-oracle.py against Penman %s. Do not edit. */\n"
                % penman.__version__
            )
            fh.write("object PenmanGolden:\n")
            fh.write(
                "  final case class Case(name: String, input: String, top: String, triples: Vector[(String, String, String, Boolean)])\n\n"
            )
            fh.write("  val cases: Vector[Case] = Vector(\n")
            for r in records:
                name = r["metadata"].get("id", "case%d" % r["index"])
                trip = ", ".join(
                    "(%s, %s, %s, %s)"
                    % (
                        json.dumps(t[0]),
                        json.dumps(t[1]),
                        json.dumps(t[2]),
                        "true" if t[3] else "false",
                    )
                    for t in r["triples"]
                )
                fh.write(
                    "    Case(%s, %s, %s, Vector(%s))%s\n"
                    % (
                        json.dumps(name),
                        json.dumps(r["input"]),
                        json.dumps(r["top"]),
                        trip,
                        "," if r is not records[-1] else "",
                    )
                )
            fh.write("  )\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
